[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[lib]
name = "sudoku"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4"
pyo3 = { version = "0.17", features = ["extension-module", "abi3-py37"] }
